[package]
name = "slightshot"
version = "0.1.0"
edition = "2021"
authors = ["dannycreations"]
license = "GPL"
repository = "https://github.com/dannycreations/slightshot"

[dependencies]
anyhow = "1.0.104"
arboard = "3.6.1"
ctrlc = "3.5.2"
fontdue = "0.9.4"
png = "0.18.1"
serde_json = "1.0.151"
softbuffer = "0.4.8"
tiny-skia = "0.12.0"
ureq = "3.4.0"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
winit = "0.30.13"

[profile.dev]
codegen-units = 16
debug = 1
incremental = true

[profile.release]
codegen-units = 1
debug = "line-tables-only"
incremental = false
lto = true
opt-level = "z"
panic = "abort"
split-debuginfo = "packed"
